### ISSUE TITLE
Kleiner Fehler in der Doku

### ISSUE THREAD

**Issue by wzolleis** [TimZolleis/mail-api#14]
Unter [Doku für Variable](https://github.com/TimZolleis/mailservice/wiki/Sending-an-email#the-variables-object) steht 

> "event.title" in this example

Aber im Beispiel gibt es kein Property mit "title"

**Comment by timzolleis** [comment]
Changed in https://github.com/TimZolleis/mailservice/wiki/Sending-an-email/a4c485289048e088e225e4121e4811979ff00c3c
