### ISSUE TITLE
Der Jobstatus wird nicht aktualisiert

### ISSUE THREAD

**Issue by wzolleis** [TimZolleis/mail-api#15]
Der Status ist immer "waiting" auch wenn die Mail schon gesendet wurde.

**Comment by timzolleis** [comment]
Is known, have to revisit status tracking and exception logging

**Comment by wzolleis** [comment]
Das Problem ist eigentlich nur, dass der Aufrufer des Service nur über den Status feststellen kann, ob die Mail gesendet wurde (egal ob das dann ok war oder z.B. wegen einer fehlerhaften Mailadresse fehlschlägt). 
D.h. der Status eines Jobs ist eine der wichtigsten Eigenschaften, die man als User benötigt.

**Comment by timzolleis** [comment]
Has been resolved in latest merge
