### ISSUE TITLE
Doppelte Mailaddress - 1x ignoriert

### ISSUE THREAD

**Issue by wzolleis** [TimZolleis/mail-api#16]
Bsp:
`
 "recipients": [
    {
      "mailAddress": "die gleiche wie unten",
      "variables": {
        "name": "Mister X"
      }
    },
    {
      "mailAddress": "die gleiche wie oben",
      "variables": {
        "name": "Mister Y"
      }
    }
  ]
`
Nur einer der beiden bekommt eine Mail.
Falls das beabsichtigt ist, wäre eventuell ein Eintrag dazu in der Doku sinnvoll.
z.B. die Mailadresse im Array der Empfänger darf nur einmal vorkommen.

**Comment by timzolleis** [comment]
Seems to be a bug, please provide more specific information.

**Comment by wzolleis** [comment]
Welche Informationen werden benötigt ?

Wenn in den Recipients 2x die gleiche Mailadresse vorkommt, so wird nur eine Mail gesendet. 
Vermutlich ist die Mailadresse "unique", das wäre ja auch ok, da man ja eher selten 2x die gleiche Mail an den gleichen Empfänger schickt (außer beim Testen). Es wäre für mich eher eine Erwähnung in der Doku wert.

**Comment by timzolleis** [comment]
Has been addressed in https://github.com/TimZolleis/mailservice/commit/23e263217cdf9d8b1b03304bf357171b357bde88 - now possible to send to the same address twice.
